mod util;

mod cpp;
mod deno;
mod dotnet;
mod elixir;
mod git;
mod go;
mod js;
mod jvm;
mod justfile;
mod mise;
mod php;
mod python;
mod ruby;
mod rust;
mod swift;

pub use cpp::CMakeDetector;
pub use deno::DenoDetector;
pub use dotnet::{CsProjDetector, SolutionDetector};
pub use elixir::MixExsDetector;
pub use git::GitDetector;
pub use go::{GoModDetector, GoWorkDetector};
pub use js::{PackageJsonDetector, PnpmWorkspaceDetector};
pub use jvm::{GradleDetector, MavenDetector};
pub use justfile::JustfileDetector;
pub use mise::MiseDetector;
pub use php::ComposerDetector;
pub use python::PythonDetector;
pub use ruby::GemfileDetector;
pub use rust::CargoTomlDetector;
pub use swift::SwiftPackageDetector;
