#[cfg(windows)]
pub static KNOWN_WINDOWS_EXE_PATTERNS: &[(&str, &str, &[&str])] = &[
    ("vscode", "Visual Studio Code", &["Code.exe"]),
    (
        "vscode-insiders",
        "Visual Studio Code Insiders",
        &["Code - Insiders.exe"],
    ),
    ("vscodium", "VSCodium", &["VSCodium.exe"]),
    ("cursor", "Cursor", &["Cursor.exe"]),
    ("windsurf", "Windsurf", &["Windsurf.exe"]),
    ("trae", "Trae", &["Trae.exe"]),
    ("zed", "Zed", &["zed.exe", "Zed.exe"]),
    (
        "antigravity",
        "Google Antigravity",
        &["Antigravity.exe", "antigravity.exe"],
    ),
    (
        "sublime",
        "Sublime Text",
        &["sublime_text.exe", "Sublime Text.exe"],
    ),
    ("atom", "Atom", &["atom.exe"]),
    ("brackets", "Brackets", &["Brackets.exe"]),
    ("geany", "Geany", &["geany.exe"]),
    ("notepad-plus-plus", "Notepad++", &["notepad++.exe"]),
    ("lapce", "Lapce", &["lapce.exe"]),
    ("intellij", "IntelliJ IDEA", &["idea64.exe"]),
    ("webstorm", "WebStorm", &["webstorm64.exe"]),
    ("pycharm", "PyCharm", &["pycharm64.exe"]),
    ("rustrover", "RustRover", &["rustrover64.exe"]),
    ("goland", "GoLand", &["goland64.exe"]),
    ("clion", "CLion", &["clion64.exe"]),
    ("phpstorm", "PhpStorm", &["phpstorm64.exe"]),
    ("rider", "Rider", &["rider64.exe"]),
    (
        "android-studio",
        "Android Studio",
        &["studio64.exe", "studio.exe"],
    ),
    ("fleet", "Fleet", &["fleet.exe"]),
    ("rstudio", "RStudio", &["rstudio.exe"]),
    ("spyder", "Spyder", &["spyder.exe"]),
    ("bluej", "BlueJ", &["bluej.exe"]),
    ("arduino", "Arduino IDE", &["arduino.exe"]),
    ("codeblocks", "Code::Blocks", &["codeblocks.exe"]),
    ("eclipse", "Eclipse", &["eclipse.exe"]),
    ("netbeans", "NetBeans", &["netbeans.exe", "netbeans64.exe"]),
];

#[cfg(not(windows))]
pub static KNOWN_UNIX_EXE_NAMES: &[(&str, &str, &[&str])] = &[
    ("vscode", "Visual Studio Code", &["code"]),
    (
        "vscode-insiders",
        "Visual Studio Code Insiders",
        &["code-insiders"],
    ),
    ("vscodium", "VSCodium", &["codium"]),
    ("cursor", "Cursor", &["cursor"]),
    ("windsurf", "Windsurf", &["windsurf"]),
    ("trae", "Trae", &["trae"]),
    ("zed", "Zed", &["zed"]),
    ("sublime", "Sublime Text", &["subl", "sublime_text"]),
    ("lapce", "Lapce", &["lapce"]),
    ("vim", "Vim", &["vim"]),
    ("neovim", "Neovim", &["nvim"]),
    ("helix", "Helix", &["hx"]),
    ("emacs", "Emacs", &["emacs"]),
    ("geany", "Geany", &["geany"]),
    ("kate", "Kate", &["kate"]),
    ("rstudio", "RStudio", &["rstudio"]),
    ("spyder", "Spyder", &["spyder"]),
    ("bluej", "BlueJ", &["bluej"]),
    ("antigravity", "Google Antigravity", &["antigravity"]),
];
