import type { Component } from "solid-js";

export const StackIconSafelist: Component = () => (
  <div class="sr-only" aria-hidden>
    <span class="iconify catppuccin--javascript" />
    <span class="iconify catppuccin--typescript" />
    <span class="iconify catppuccin--python" />
    <span class="iconify catppuccin--rust" />
    <span class="iconify catppuccin--go" />
    <span class="iconify catppuccin--csharp" />
    <span class="iconify catppuccin--deno" />
    <span class="iconify catppuccin--php" />
    <span class="iconify catppuccin--ruby" />
    <span class="iconify catppuccin--elixir" />
    <span class="iconify catppuccin--kotlin" />
    <span class="iconify catppuccin--java" />
    <span class="iconify catppuccin--swift" />
    <span class="iconify catppuccin--cpp" />
    <span class="iconify catppuccin--text" />
    <span class="iconify catppuccin--node" />
    <span class="iconify catppuccin--nodejs" />
    <span class="iconify catppuccin--bun" />
    <span class="iconify catppuccin--npm" />
    <span class="iconify catppuccin--yarn" />
    <span class="iconify catppuccin--pnpm" />
    <span class="iconify catppuccin--composer" />
    <span class="iconify catppuccin--maven" />
    <span class="iconify catppuccin--gradle" />
    <span class="iconify catppuccin--git" />
    <span class="iconify catppuccin--github" />
    <span class="iconify catppuccin--folder-node" />

    {/* IDE Icons */}
    <span class="iconify devicon-plain--vscode" />
    <span class="iconify devicon-plain--vscodium" />
    <span class="iconify devicon-plain--visualstudio" />
    <span class="iconify devicon-plain--intellij" />
    <span class="iconify devicon-plain--webstorm" />
    <span class="iconify devicon-plain--pycharm" />
    <span class="iconify devicon-plain--goland" />
    <span class="iconify devicon-plain--clion" />
    <span class="iconify devicon-plain--phpstorm" />
    <span class="iconify devicon-plain--rider" />
    <span class="iconify devicon-plain--androidstudio" />
    <span class="iconify devicon-plain--vim" />
    <span class="iconify devicon-plain--neovim" />
    <span class="iconify devicon-plain--eclipse" />
    <span class="iconify devicon-plain--netbeans" />
    <span class="iconify devicon-plain--arduino" />
    <span class="iconify devicon-plain--rstudio" />
    <span class="iconify mdi--target" />
    <span class="iconify mdi--surfing" />
    <span class="iconify mdi--robot" />
    <span class="iconify mdi--rocket-launch" />
    <span class="iconify mdi--language-rust" />
    <span class="iconify mdi--text-box-outline" />
    <span class="iconify mdi--alpha-z-box" />
    <span class="iconify mdi--lightning-bolt" />
    <span class="iconify mdi--hexagon" />
    <span class="iconify mdi--note-edit" />
    <span class="iconify mdi--atom" />
    <span class="iconify mdi--code-brackets" />
    <span class="iconify mdi--text-box-edit" />
    <span class="iconify mdi--text" />
    <span class="iconify mdi--code-tags" />
    <span class="iconify mdi--star" />
    <span class="iconify mdi--text-box" />
    <span class="iconify mdi--application-braces" />
    <span class="iconify mdi--notebook" />
    <span class="iconify mdi--spider" />
    <span class="iconify mdi--snake" />
    <span class="iconify mdi--coffee" />
    <span class="iconify mdi--foot-print" />
    <span class="iconify mdi--microphone" />
    <span class="iconify mdi--satellite" />
    <span class="iconify mdi--application-edit-outline" />
    <span class="iconify mdi--chevron-down" />
    <span class="iconify mdi--check" />

    {/* Issue Panel Icons */}
    <span class="iconify mdi--alert-circle-outline" />
    <span class="iconify mdi--check-circle-outline" />
    <span class="iconify mdi--pound" />
    <span class="iconify mdi--clock-outline" />
    <span class="iconify mdi--account-circle-outline" />
    <span class="iconify mdi--pencil" />
    <span class="iconify mdi--close-circle-outline" />
    <span class="iconify mdi--trash-can-outline" />
    <span class="iconify mdi--arrow-left" />
    <span class="iconify mdi--github" />
    <span class="iconify mdi--plus" />
    <span class="iconify mdi--stop" />

    {/* Shell Icons */}
    <span class="iconify mdi--powershell" />
    <span class="iconify mdi--console" />
    <span class="iconify mdi--nix" />
    <span class="iconify mdi--bash" />
    <span class="iconify mdi--fish" />
    <span class="iconify mdi--console-line" />

    {/* Git Icons */}
    <span class="iconify mdi--git" />
    <span class="iconify mdi--arrow-up" />
    <span class="iconify mdi--arrow-down" />
    <span class="iconify mdi--upload" />
    <span class="iconify mdi--download" />

    {/* Screenshot Icons */}
    <span class="iconify mdi--camera" />
    <span class="iconify mdi--cog-outline" />
    <span class="iconify mdi--monitor-screenshot" />
    <span class="iconify mdi--monitor" />
    <span class="iconify mdi--monitor-multiple" />
    <span class="iconify mdi--crop" />
    <span class="iconify mdi--application-outline" />
    <span class="iconify mdi--arrow-top-right" />
    <span class="iconify mdi--rectangle-outline" />
    <span class="iconify mdi--draw" />
    <span class="iconify mdi--format-text" />
    <span class="iconify mdi--marker" />
    <span class="iconify mdi--undo" />
    <span class="iconify mdi--redo" />
    <span class="iconify mdi--clipboard-text-multiple" />
    <span class="iconify mdi--content-save" />

    {/* Canvas Icons */}
    <span class="iconify mdi--git" />
    <span class="iconify mdi--play-circle-outline" />
    <span class="iconify mdi--docker" />
    <span class="iconify mdi--jira" />
    <span class="iconify mdi--check-decagram-outline" />
    <span class="iconify mdi--cloud-check-outline" />
    <span class="iconify mdi--notebook-outline" />
    <span class="iconify mdi--file-code-outline" />
    <span class="iconify mdi--console" />
    <span class="iconify mdi--web" />
    <span class="iconify mdi--server-network" />
    <span class="iconify mdi--application-outline" />
    <span class="iconify mdi--monitor-dashboard" />
    <span class="iconify mdi--package-variant-closed" />
    <span class="iconify mdi--view-dashboard-outline" />
    <span class="iconify mdi--tools" />
    <span class="iconify mdi--link-variant" />
    <span class="iconify mdi--arrow-right-circle-outline" />
    <span class="iconify mdi--window-maximize" />
    <span class="iconify mdi--window-minimize" />
    <span class="iconify mdi--resize-bottom-right" />
    <span class="iconify mdi--fit-to-page-outline" />
    <span class="iconify mdi--grid" />
    <span class="iconify mdi--cursor-move" />
    <span class="iconify mdi--source-branch" />
    <span class="iconify mdi--view-quilt-outline" />
    <span class="iconify mdi--sync" />
    <span class="iconify mdi--open-in-new" />
    <span class="iconify mdi--refresh" />
    <span class="iconify mdi--power" />
    <span class="iconify mdi--play" />
    <span class="iconify mdi--cloud-upload" />
    <span class="iconify mdi--swap-horizontal" />
    <span class="iconify mdi--broom" />
    <span class="iconify mdi--lock-outline" />
    <span class="iconify mdi--cancel" />
  </div>
);
