import type { BlueprintDefinition } from "./types";

export const BUILTIN_BLUEPRINTS: BlueprintDefinition[] = [
  {
    id: "fullstack-web",
    name: "Full-Stack Web App",
    description:
      "Dev server, Git branch, and live local port preview. CI and deploy nodes appear automatically when detected.",
    scope: "fullstack",
    supportedScopes: ["fullstack", "monorepo"],
    icon: "mdi--web",
    defaultNodes: [
      {
        id: "node-git",
        nodeType: "git",
        title: "Git Repository",
        x: 60,
        y: 80,
        width: 280,
        height: 220,
        isPinned: true,
      },
      {
        id: "node-task",
        nodeType: "task",
        title: "Dev Server (:3000)",
        x: 400,
        y: 80,
        width: 320,
        height: 240,
        isPinned: true,
      },
      {
        id: "node-web-preview",
        nodeType: "webPreview",
        title: "Live Web Preview (:3000)",
        x: 780,
        y: 340,
        width: 440,
        height: 320,
      },
      {
        id: "node-web-tools",
        nodeType: "webTools",
        title: "WebTools (linked)",
        x: 1252,
        y: 340,
        width: 420,
        height: 320,
        dataJson: JSON.stringify({ targetId: "node-web-preview" }),
      },
    ],
    defaultWires: [
      {
        id: "wire-web-tools",
        sourceId: "node-web-preview",
        targetId: "node-web-tools",
        wireType: "stream",
        status: "nominal",
        annotation: "Live preview telemetry",
      },
    ],
  },
  {
    id: "backend-api",
    name: "Backend & Microservice",
    description:
      "API server runner, Live terminal stream, and OpenAPI preview. CI and deploy nodes appear automatically when detected.",
    scope: "server",
    supportedScopes: ["server", "fullstack"],
    icon: "mdi--server-network",
    defaultNodes: [
      {
        id: "node-git",
        nodeType: "git",
        title: "Git Repository",
        x: 60,
        y: 80,
        width: 280,
        height: 220,
        isPinned: true,
      },
      {
        id: "node-task",
        nodeType: "task",
        title: "API Server",
        x: 400,
        y: 80,
        width: 320,
        height: 240,
      },
      {
        id: "node-terminal",
        nodeType: "terminal",
        title: "Interactive Shell",
        x: 60,
        y: 360,
        width: 320,
        height: 240,
      },
    ],
    defaultWires: [],
  },
  {
    id: "spa-client",
    name: "Single-Page Application",
    description:
      "Vite dev server, Component preview, Git branch, Localhost preview, and PR review status.",
    scope: "spa",
    supportedScopes: ["spa"],
    icon: "mdi--application-outline",
    defaultNodes: [
      {
        id: "node-git",
        nodeType: "git",
        title: "Git Repository",
        x: 60,
        y: 80,
        width: 280,
        height: 220,
        isPinned: true,
      },
      {
        id: "node-task",
        nodeType: "task",
        title: "Vite Dev Server (:5173)",
        x: 400,
        y: 80,
        width: 320,
        height: 240,
      },
      {
        id: "node-web-preview",
        nodeType: "webPreview",
        title: "Component / SPA View",
        x: 780,
        y: 80,
        width: 460,
        height: 380,
      },
      {
        id: "node-web-tools",
        nodeType: "webTools",
        title: "WebTools (linked)",
        x: 1272,
        y: 80,
        width: 420,
        height: 340,
        dataJson: JSON.stringify({ targetId: "node-web-preview" }),
      },
      {
        id: "node-notes",
        nodeType: "notes",
        title: "Design Notes / Scratchpad",
        x: 60,
        y: 360,
        width: 280,
        height: 220,
      },
    ],
    defaultWires: [
      {
        id: "wire-task-web",
        sourceId: "node-task",
        targetId: "node-web-preview",
        wireType: "stream",
        status: "nominal",
        annotation: "Live hot module replacement",
      },
      {
        id: "wire-web-tools",
        sourceId: "node-web-preview",
        targetId: "node-web-tools",
        wireType: "stream",
        status: "nominal",
        annotation: "Live preview telemetry",
      },
    ],
  },
  {
    id: "desktop-app",
    name: "Desktop Application",
    description:
      "Tauri / Electron runner, Rust/C++ compiler status, Window preview, and Release bundler.",
    scope: "desktop",
    supportedScopes: ["desktop"],
    icon: "mdi--monitor-dashboard",
    defaultNodes: [
      {
        id: "node-git",
        nodeType: "git",
        title: "Git Repository",
        x: 60,
        y: 80,
        width: 280,
        height: 220,
        isPinned: true,
      },
      {
        id: "node-task",
        nodeType: "task",
        title: "Desktop Dev Runner",
        x: 400,
        y: 80,
        width: 320,
        height: 240,
      },
      {
        id: "node-terminal",
        nodeType: "terminal",
        title: "Cargo / Native Build Output",
        x: 400,
        y: 380,
        width: 360,
        height: 260,
      },
      {
        id: "node-file-preview",
        nodeType: "filePreview",
        title: "Configuration Preview",
        x: 780,
        y: 80,
        width: 560,
        height: 380,
      },
    ],
    defaultWires: [
      {
        id: "wire-git-task",
        sourceId: "node-git",
        targetId: "node-task",
        wireType: "pipeline",
        status: "nominal",
        annotation: "Native build pipeline",
      },
    ],
  },
  {
    id: "cli-tool",
    name: "CLI & System Tool",
    description:
      "Interactive terminal runner, Binary build task, Git commit graph, and Unit test runner.",
    scope: "cli",
    supportedScopes: ["cli"],
    icon: "mdi--console",
    defaultNodes: [
      {
        id: "node-git",
        nodeType: "git",
        title: "Git Repository",
        x: 60,
        y: 80,
        width: 280,
        height: 220,
        isPinned: true,
      },
      {
        id: "node-terminal",
        nodeType: "terminal",
        title: "Interactive Shell / CLI Run",
        x: 400,
        y: 80,
        width: 440,
        height: 320,
      },
      {
        id: "node-task",
        nodeType: "task",
        title: "Build / Test Tasks",
        x: 60,
        y: 360,
        width: 280,
        height: 240,
      },
    ],
    defaultWires: [
      {
        id: "wire-task-term",
        sourceId: "node-task",
        targetId: "node-terminal",
        wireType: "execution",
        status: "nominal",
        annotation: "CLI runner",
      },
    ],
  },
  {
    id: "package-library",
    name: "Package / Library",
    description: "Test suite runner, Type checker / linter, Semver bump status, and Git graph.",
    scope: "library",
    supportedScopes: ["library"],
    icon: "mdi--package-variant-closed",
    defaultNodes: [
      {
        id: "node-git",
        nodeType: "git",
        title: "Git & Release Tags",
        x: 60,
        y: 80,
        width: 280,
        height: 220,
        isPinned: true,
      },
      {
        id: "node-task",
        nodeType: "task",
        title: "Test Suite Runner",
        x: 400,
        y: 80,
        width: 320,
        height: 240,
      },
      {
        id: "node-notes",
        nodeType: "notes",
        title: "Changelog / Export Notes",
        x: 400,
        y: 380,
        width: 320,
        height: 220,
      },
    ],
    defaultWires: [],
  },
  {
    id: "solo-scrum",
    name: "Solo Scrum / Feature Tracker",
    description:
      "Git Branch & Commit graph and Notes. CI and deploy nodes appear automatically when detected.",
    scope: "monorepo",
    supportedScopes: ["fullstack", "server", "spa", "desktop", "monorepo"],
    icon: "mdi--view-dashboard-outline",
    defaultNodes: [
      {
        id: "node-git",
        nodeType: "git",
        title: "Git Repository",
        x: 60,
        y: 80,
        width: 280,
        height: 220,
        isPinned: true,
      },
      {
        id: "node-notes",
        nodeType: "notes",
        title: "Daily Standup Scratchpad",
        x: 400,
        y: 80,
        width: 280,
        height: 220,
      },
    ],
    defaultWires: [],
  },
];
